//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_CRUD_MVC_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Empno { get; set; }
        public string name { get; set; }
        public string dept { get; set; }
        public string desig { get; set; }
        public Nullable<int> basic { get; set; }
    }
}
